BC-5999. Таблица и сущность Payment
CorporationX/payment_service pull request #11
Opened 2023-09-11 15:19 UTC by Dlakares

Совершил миграцию, создал таблицу Payments.
Добавил сущность Payment и репозиторий к ней

2023-09-12 07:29 UTC, AntonRudnikovskiy approved these changes
аппрув

2023-09-12 07:29 UTC, AntonRudnikovskiy commented on src/main/java/faang/school/paymentservice/model/Payment.java
> +    private PaymentStatus status;
если это у тебя enum можно добавить @Enumerated(EnumType.STRING)

2023-09-16 15:15 UTC, kkkooolllyyyaaa requested changes
👌 , пару замечаний

2023-09-16 15:15 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__payment-service_payment-table.sql
> +    receiver_account_id BIGINT NOT NULL,
Обычно кидают запрос по номерам счетов, а id это просто внутренний id нашей системы, его вовне особо никто не знает)

2023-09-16 15:15 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/paymentservice/model/Payment.java
> +    private PaymentStatus status;
согласен, лучше в строчке хранить

2023-09-25 17:29 UTC, merged