BC-5994. Create payment
CorporationX/payment_service pull request #19
Opened 2023-09-22 14:25 UTC by Dlakares

2023-09-22 14:26 UTC, Dlakares commented
Коммит с изменениями этой подтаски - https://github.com/CorporationX/payment_service/pull/19/commits/217f6d47ef0be8ac54251090b0fb47951f27df3c

2023-09-22 14:26 UTC, Dlakares commented
Коммит с изменениями этой подтаски - https://github.com/CorporationX/payment_service/pull/19/commits/217f6d47ef0be8ac54251090b0fb47951f27df3c

2023-09-24 13:06 UTC, kkkooolllyyyaaa requested changes
пару комментов)

2023-09-24 13:06 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/paymentservice/dto/PaymentStatus.java
> +    SUCCESS, AUTHORIZATION
Ещё REFUND и FAILURE

2023-09-24 13:06 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/paymentservice/service/payment/PaymentService.java
> +            return paymentMapper.toDto(optionalPayment.get());
Тут если sender, reciever account id, amount или currency отличаются, то нужно исключение кинуть. Клиент хотел совершить платеж, а ты ему совсем другой по смыслу платеж отдашь

2023-09-25 17:28 UTC, kkkooolllyyyaaa approved these changes
👍

2023-09-25 17:29 UTC, merged