BC-6000. Payment event publisher
CorporationX/payment_service pull request #24
Opened 2023-09-25 13:56 UTC by Dlakares

2023-09-25 13:57 UTC, Dlakares commented
Коммит с изменениями этой подтаски [https://github.com/CorporationX/payment_service/pull/24/commits/6c6c8e97eef19753d56b9186a3c8d97dc377397b](тут)

2023-10-02 00:13 UTC, Rvze requested changes
неплохо, есть пару недочетов, но пока что уверенно идешь)

2023-10-02 00:13 UTC, Rvze commented on src/main/java/faang/school/paymentservice/service/payment/AccountServiceWorker.java
я так и не понял зачем этот класс

2023-10-02 00:13 UTC, Rvze commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    }
мне кажется, одного топика маловато. Лучше было бы иметь все 3 топика, чтобы `account_service` отдельно слушал каждое событие. А то может быть такое, что `account_service` слушает только 1 топик, где подряд будут идти события одного типа и будет работать только один функционал обработки

2023-10-02 00:13 UTC, Rvze commented on src/main/java/faang/school/paymentservice/service/payment/PaymentService.java
> +    }
кмк `sendEvent` здесь не должен быть, это не обязанность метода `clearPayment`.

2023-10-02 00:13 UTC, Rvze commented on src/main/java/faang/school/paymentservice/service/payment/PaymentService.java
> +    }
лучше `sendEvent` вызывать в главном методе

2023-11-07 14:09 UTC, merged