Создание функционала по оплате DMS
CorporationX/payment_service pull request #26
Opened 2023-10-08 14:13 UTC by kxnvg

2023-10-11 22:12 UTC, kkkooolllyyyaaa requested changes
Есть моментики)

2023-10-11 22:12 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/paymentservice/service/PaymentService.java
> +                () -> new EntityNotFoundException("This payment doesn't exist"));
Вроде повторяется, можжно вынести

2023-10-11 22:12 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/paymentservice/service/PaymentService.java
> +                payment.getIdempotencyKey(), payment.getCreatedAt(), payment.getStatus());
Нее, нужно дтошку вернуть а не строчку) Этот метод будет вызываться на условном фронте и проверяться статус

2023-10-11 22:12 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__payment-service_payment.sql
> +    idempotency_key UUID NOT NULL,
опять же, тут и ниже лучше не завязываться жестко на UUID

2023-10-11 22:12 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__payment-service_payment.sql
> +CREATE INDEX status_index ON payment(status);
это индекс сам по себе избыточен)

2023-10-11 22:12 UTC, kkkooolllyyyaaa commented on src/main/resources/db/changelog/changeset/V001__payment-service_payment.sql
> +CREATE INDEX posted_index ON outbox_payment(is_posted);
тоже избыточен. true/false особо не проиндецируешь (не выгодно)

2023-10-12 11:06 UTC, kxnvg commented on src/main/java/faang/school/paymentservice/service/PaymentService.java
> +                () -> new EntityNotFoundException("This payment doesn't exist"));
В других местах вынесено вместе с другой повторяющейся логикой. Здесь не актуально выносить получается

2023-10-15 22:31 UTC, kkkooolllyyyaaa approved these changes
👍

2023-10-15 22:31 UTC, merged