start of solution task BJS2-27448 - Конвертер валют
CorporationX/payment_service pull request #64
Opened 2024-09-30 18:38 UTC by wmwmaks

2024-10-01 08:19 UTC, SharkB38 requested changes

2024-10-01 08:19 UTC, SharkB38 commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        }
Надо еще сброосить флаг

2024-10-01 08:28 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        }
Да, точно. Хотя и так работало же, но сделаю

2024-10-01 10:19 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeConfig.java
> +public class CurrencyExchangeConfig {
Ты где-то используешь CurrencyExchangeConfig? Я кажется не заметил)

2024-10-01 10:21 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
> +    private final CurrencyExchangeServiceImpl currencyExchangeService;
Скорее всего, ты хотел сюда инжектить интерфейс, а не реализацию?)

2024-10-01 10:31 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
>          );
Порекомендовал бы убрать ResponseEntity и возвращать PaymentResponse, также можешь рассмотреть вариант с добавлением toCurrency в PaymentRequest, тогда можно в сервис только дто передавать) Я бы ещё наверное из сервиса возвращал не message, а сам же PaymentRequest с обновлённой суммой и новым статусом, например - TO_ACCEPT, чтобы клиент мог подтвердить платёж) Там ещё можно многого придумать, всё на твоё усмотрение)

2024-10-01 10:34 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeService.java
> +                               BigDecimal amount, String appId);
Писал про интерфейс выше, а то этот интерфейс и метод в нём, не используется)

2024-10-01 10:36 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
>          );
Изначально добавлял "toCurrency в PaymentRequest", а потом решил, что можно по-другому сделать, чтобы не трогать заготовку. Тут и правда можно много чего сделать по разному и непонятно, как лучше или должно быть.

2024-10-01 10:39 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
>          );
Буду ждать еще мнений от команды и Маши. Есть ощущение, что с реализацией PaymentService надо будет менять логику моей задачи. Вообще сомнения по каждой строчке. Непонятно и страшно😃

2024-10-01 10:46 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeConfig.java
> +public class CurrencyExchangeConfig {
А вот как будто бы и нет. Везде так же из yaml достаю. Исправлю.

2024-10-01 10:47 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
> +    private final CurrencyExchangeServiceImpl currencyExchangeService;
Снова перепутал, исправил 😅

2024-10-01 10:59 UTC, SharkB38 approved these changes

2024-10-01 11:03 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
В идеале, твои методы конвертации должны быть независимы от вида валюты) Я понимаю [Open Exchange Rates] только default USD возвращает, но кажется Никита делает кэш с курсами валют и там будут все валюты, и тебе придётся всё переделывать, может пока он не закончил сделать класс заглушку, которая хранит разные валюты, брать оттуда разные курсы валют и попробовать реализовать методы которые работают со всеми валютами?) Я просто советую, если у тебя нет задач конечно)

2024-10-01 11:04 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        return String.format("Dear friend! Thank you for your purchase!");
Порекомендовал бы также переделать методы, если надумаешь) А то метод getMessage по идее не должен запускать все методы в сервисе, он и конвертирует, добавляет комиссию, а должен вроде только сообщение возвращать)

2024-10-01 11:06 UTC, ArstanSubanov approved these changes
Го на ревью к Маше)

2024-10-01 11:19 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
Звучит логично. Подумаю, как это можно сделать. Сразу не получилось сообразить. Если что в четверг мне на дейлике объясните)

2024-10-01 11:19 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        return String.format("Dear friend! Thank you for your purchase!");
Тоже справедливо. Попробую исправить

2024-10-01 11:55 UTC, soulasphyxia commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
максим, если я правильно понимаю, ты сейчас обрабатываешь только ситуации, когда можно с USD какую-то конвертацию сделать?

2024-10-01 11:57 UTC, soulasphyxia commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
на самом деле, зная отношение двух валют к другой, можно посчитать их отношение между собой, и, на мне кажется, бесплатной апишки хватит для наших целей, хотя конечно, это не прям-прям точно будет

2024-10-01 12:10 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
Нет ,конвертации из любой в любую. (Из тех, которые прописаны в енаме). Когда валюта изначальная не usd, сначала ее в usd привожу, а потом оттуда уже в нужную, какую запрашивали. Это костыль из-за того ,что base всегда usd. 
Наверное, это можно сделать красивее, но я пока не придумал как. Так - работает, я проверял в постмане)

2024-10-01 12:17 UTC, soulasphyxia commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
попробуй поделить их) как я понял тебе приходит список того, сколько стоит 1 USD в разных валютах? тогда, например, мы знаем что 1 USD = 93 RUB и 1 USD = 7 CYN, и мы можем найти, что 1 CYN = 93/7 = 13.24, а 1 RUB = 7/93 = 0.0755 CYN

2024-10-01 12:17 UTC, soulasphyxia commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
или я не так понимаю..

2024-10-01 12:21 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
То, что ты пишешь, точно имеет смысл. Попробую

2024-10-02 20:25 UTC, mysosnovskaya requested changes

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/client/FeignConfig.java
> +    public FeignUserInterceptor feignPaymentInterceptor(UserContext userContext) {
Так он Payment или User интерцептор?)

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeConfig.java
> +@Configuration
Эта аннотация не нужна

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
> +    String appId;
А модификаторы?

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
> +    public ResponseEntity<PaymentResponse> sendPayment(
ResponseEntity давай удалим

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/client/OpenExchangesRatesClient.java
> +    @GetMapping()
Если в скобках нечего писать, то лучше их удалить

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    appId:
Нужно что-то добавить сюда, чтобы у всех работало. Нужна информация от меня, верно?

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    private final String appId = exchangeConfig.getAppId();
Так это appId в результате приходит в convertCurrency как параметр или используется из поля? Нужно что-то одно оставить

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        if (currency.name().equals("USD")) {
Почему сравниваешь через name? Можно же просто Currency.USD использовать

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        if (toCurrency.name().equals("USD")) {
Аналогично

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        BigDecimal convertedAmount = usdAmount.multiply(BigDecimal.valueOf(toRate));
`return usdAmount.multiply(BigDecimal.valueOf(toRate));`

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        BigDecimal usdAmount = amount.divide(BigDecimal.valueOf(fromRate), 4, RoundingMode.HALF_UP);
Логику divide и multiply нужно вынести в отдельные приватные методы, т.к. она повторяется

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    }
Виталя, спасибо!) Хорошая идея

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    public BigDecimal addCommission(BigDecimal amount, double commission, Currency currency, Currency toCurrency) {
А в интерфейсе этого метода нет. Тогда он не должен быть public

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        if (currency.name().equals(toCurrency.name())) {
Почему не `currency.equals(toCurrency)`?

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        isAddCommission = true;
Похоже, ты забыл, что мы работаем в многопоточной среде и поле isAddCommission будет меняться постоянно многими потоками. И не факт, что когда ты вызовешь метод getMessage, значение isAddCommission останется нужным (= что его никто не изменит). А если ещё и про кэш процессора вспомнить... =)

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        return String.format("Dear friend! Thank you for your purchase!");
Абсолютно согласна. getMessage совсем не getMessage получился

2024-10-02 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        return String.format("Dear friend! Thank you for your purchase!");
Ещё не понимаю, почему, когда комиссия есть, то мы вежливые и расписываем, сколько в какую валюту перевели, а когда комиссии нет, то просто отписка... Хотя нет, понимаю 😆 
Нужно единообразно сделать

2024-10-02 20:35 UTC, wmwmaks commented on src/main/resources/application.yaml
> +    appId:
Не, я могу свой вставить. Добавлю

2024-10-03 10:28 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +        return String.format("Dear friend! Thank you for your purchase!");
Изначально вообще было так, что комиссия была даже, когда никакой конвертации не происходило 😅 Получается, если комиссии нет, то писать что-то типа "You have to pay commission 0." ?

2024-10-04 19:58 UTC, mysosnovskaya requested changes
Жду тестов)

2024-10-04 19:58 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeParams.java
> +@Configuration
Я спросила у gpt и посмотрела в своих проектах, везде без Configuration всё получается) Загадка прям, но давай разберемся с этим вопросом и докопаемся до истины

2024-10-04 19:58 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeService.java
> +    BigDecimal getAmountNewCurrency(PaymentRequest dto, Currency toCurrency);
Не понимаю здесь это "New". Может это convertToCurrency? Может это convertWithoutComission? А если так, то можно нужно сделать один convert метод с флагом: добавлять комиссию или нет?

2024-10-04 19:58 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeServiceImpl.java
> +    public BigDecimal addCommission(BigDecimal amount) {
Override не хватает здесь и в следующем методе

2024-10-04 20:03 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeParams.java
> +@Configuration
🤷‍♂️
Я только за)

2024-10-04 20:29 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeService.java
> +    BigDecimal getAmountNewCurrency(PaymentRequest dto, Currency toCurrency);
Мне кажется, что нет смысла рассматривать вариант логики без комиссии. Если нужно просто оплатить пускай идут на /payment, а у меня /exchange. И что тогда лучше оставить один метод convertWithCommission(), который будет конвертировать и сразу добавлять комиссию?

2024-10-04 20:36 UTC, wmwmaks commented on src/main/java/faang/school/paymentservice/config/currency/CurrencyExchangeParams.java
> +@Configuration
Ладно, я, кажется, разобрался. Достаточно было добавить @EnableConfigurationProperties(CurrencyExchangeParams.class) или @ConfigurationPropertiesScan в класс конфигурации. Почему-то раньше оно не работало, возможно, мешало что-то другое, что уже пофиксил раньше. Или я просто тупил

2024-10-04 21:11 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyExchangeService.java
> +    BigDecimal getAmountNewCurrency(PaymentRequest dto, Currency toCurrency);
Да, давай так. Возможно и отдельный на addComission не нужно, я с трудом представляю, кому это может потребоваться.

2024-10-05 16:00 UTC, mysosnovskaya approved these changes

2024-10-05 16:29 UTC, merged