Feature bjs2 27459
CorporationX/payment_service pull request #66
Opened 2024-10-01 19:18 UTC by KarabbasBarabas

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    @Scheduled(fixedDelayString = "${currency-rate-fetcher.cron}")
Тут вроде cron нужен, а не fixedDelayString? Переменная в properties называется cron)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public Map<Currency, Double> checkHealth() {
Мне кажется этот класс должен отвечать только за запуск джобы по расписанию, для эндпоинта лучше выделить отдельный класс CurrencyController например)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
ConcurrentHashMap не подходит?)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private ReadWriteLock lock;
Может лучше сделать final и просто инжектить через @RequiredArgsConstructor? Можно также убрать @Qualifier)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +        lock.readLock().unlock();
Я читал, что хорошей практикой является оборачивать lock в блок try/finally, так как если при выполнении кода выскочит исключение, то unlock не выполнится и поток заблокируется, конечно в твоём коде такое вряд ли возникнет)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        log.info("Сохранён курс валют: " + rates);
Мне кажется, нужно по каждой валюте из класса Currency сделать запрос, так как получается что кэш будет хранится только по одной валюте, указанной в baseCurrency, получается по другим валютам будут по формуле высчитываться. К тому же в задании указано использовать WebClient, который поддерживает асинхронные запросы, а не FeignClient. Думаю, это намёк в цикле запускать асинхронные запросы по каждой валюте к API и получать их, как думаешь? Я бы ещё в кэше хранил дату, на которые получены курсы валют, чтобы в любой момент проверить что курсы актуальные)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
Может просто бросать исключение в GlobalExceptionHandler ловить её и логировать весь stackTrace?)

2024-10-02 08:30 UTC, ArstanSubanov commented on src/main/resources/application.yaml
> +  access_key: 2013557734a6dbc4c96e59020af22c48
access_key вроде твой личный? Может тут просто указывать путь к файлу, откуда можно будет взять access_key?)

2024-10-02 11:58 UTC, SharkB38 commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        log.info("Сохранён курс валют: " + rates);
Если там тот же сервис что и у Максима, там можно получить только курсы доллара

2024-10-02 12:04 UTC, SharkB38 approved these changes

2024-10-02 12:04 UTC, SharkB38 commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String baseCurrency;
Опять нет отступов перед аннотациями, и логи на русском. Вот например смотри, когда у тебя несколько аннотаций идет, видно, что отступ бы отлично визуально разделил поля.

2024-10-02 15:23 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        log.info("Сохранён курс валют: " + rates);
Вроде бы у них разные сервисы, в этом сервисе ограничение только на кол-во запросов кажется было, или я плохо прочитал документацию)

2024-10-02 16:59 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    @Scheduled(fixedDelayString = "${currency-rate-fetcher.cron}")
забыл поменять переменную, если через крон делать, то раз в сутки не понятно когда запустится, а через fixedDelay - сразу после запуска приложения, по крайней мере у меня так было

2024-10-02 17:00 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public Map<Currency, Double> checkHealth() {
я думаю это не принципиально

2024-10-02 17:00 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
у меня лок есть, думаешь этого не достаточно?

2024-10-02 17:01 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private ReadWriteLock lock;
кто-то тоже может в своем классе потом использовать ReadWriteLock, нужно их как-то различать

2024-10-02 17:02 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +        lock.readLock().unlock();
согласен, нужно добавить

2024-10-02 17:05 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        log.info("Сохранён курс валют: " + rates);
насчёт даты согласен, насчёт валюты - не понял зачем. У нас есть условно "наша" валюта, в которой мы принимаем платежи(сейчас это EUR, потому что только его можно получать с бесплатным аккаунтом на внешнем сервисе). И нам нужен курс только относительно этой валюты всех других валют

2024-10-02 17:05 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
может да, пока не знаю как это делать

2024-10-02 17:06 UTC, KarabbasBarabas commented on src/main/resources/application.yaml
> +  access_key: 2013557734a6dbc4c96e59020af22c48
можно, не знал что так можно сделать

2024-10-03 03:20 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    @Scheduled(fixedDelayString = "${currency-rate-fetcher.cron}")
Можешь попробовать поставить cron, который запускается каждую минуту, потестить, а потом поменять на раз в сутки

2024-10-03 18:56 UTC, mysosnovskaya requested changes

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    @Value("${currency-rate-fetcher.url}")
Тут точно нужна пустая строка перед аннотацией

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    public WebClient webClient() {
Надо метод назвать как-то так, чтобы было понятно, для какого именно сервиса (url) это клиент

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    public ReadWriteLock readWriteLock() {
На дейлике договорились удалить бин

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public void updateActualCurrencyRate() {
Этот метод должен быть в отдельном классе-планировщике. Контроллер отвечает только за общение с внешним миром по rest. А у планировщика принципиально другой смысл

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
А зачем писать самостоятельно блокировку, если уже есть готовая и к тому же более эффективная?) Или по каким-то причинам ConcurrentHashMap не подходит?

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +                .uri(uriBuilder -> uriBuilder
Как обсудили на дейли, это нужно вынести в отдельный класс-клиент

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        String baseCurrency = currencyRateCache.getBaseCurrency();
Почему кэш отвечает за то, какая у нас базовая валюта? Кэшу вообще должно быть всё равно на это)

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String baseCurrency;
А зачем это поле здесь?

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
NullPointerException здесь не подходит, это о другом. Это когда у null вызвали какой-то метод. Нужно либо своё реализовать, либо RuntimeException кинуть

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            String message = "An empty list of the exchange rate was received from the exchange rate service.Currency exchange rate update failed";
An empty list - не совсем правда, он не пустой, его вообще нет)

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
Про исключение аналогично

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +  fixedDelay: 86400000 # раз в сутки
Хорошо, что комментарий оставил, хорошая практика 👍

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +  access_key: 2013557734a6dbc4c96e59020af22c48
Я думаю, для нас удобнее оставить так. Иначе каждому, кто захочет локально запустить этот сервис, придется делать себе этот ключ. Неудобно. Если Никита не против, пусть все пользуются его личным ключом =)

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String date;
Так, а дата здесь зачем? Не вижу, чтобы она где-то была нужна

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        currencyRateCache.setDate(rateDto.date());
Мне кажется, дата это лишнее. Пока не вижу нигде её использования

2024-10-03 18:56 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +    public CurrencyRateDto checkHealth() {
А почему это "checkHealth"? Это же получение информации о курсах разных валют

2024-10-03 19:05 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        log.info("Сохранён курс валют: " + rates);
Тут вопрос к тому, как планируется использовать этот сервис, что через него будет оплачиваться. Тогда станет понятно, нужны ли нам другие курсы. Если посмотреть на 
https://github.com/CorporationX/payment_service/blob/hydra-master-stream6/src/main/java/faang/school/paymentservice/dto/PaymentRequest.java#L16
то увидим, что приходит только одна валюта, а не две. Я отсюда сделаю вывод, что используется одна базовая валюта и все курсы к ней (как сейчас у Никиты). Но @KarabbasBarabas, если тебе интересно добавить сюда асинхронность, как предложил Арстан, то давай сделаем) Необязательно, конечно, просто ради практики

2024-10-03 19:05 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public Map<Currency, Double> checkHealth() {
Написала в ревью, это принципиально

2024-10-03 19:07 UTC, mysosnovskaya requested changes

2024-10-03 19:07 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    @Scheduled(fixedDelayString = "${currency-rate-fetcher.fixedDelay}")
А если сервис запустился в 23:50, то весь следующий день он будет работать с неактуальными (вчерашними) курсами? Так дело не пойдет) Обновлять нужно в 00:00 (можно в 00:01). При запуске приложения можно специально отдельно вызвать)

2024-10-04 02:48 UTC, ArstanSubanov commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String date;
Я это предложил) Я думал так, что если планировщик по какой-либо причине не отработал и кэш не обновился, нужен был бы какой-то флаг, что он актуальный, и первое что пришло в голову это хранить дату, чтобы в случае чего можно было бы проверить на актуальность данных) Может быть, она и не нужна)

2024-10-05 08:35 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    @Value("${currency-rate-fetcher.url}")
поправил

2024-10-05 08:37 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    public WebClient webClient() {
поправил

2024-10-05 08:38 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/config/CurrencyRateConfig.java
> +    public ReadWriteLock readWriteLock() {
поправил

2024-10-05 08:42 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public void updateActualCurrencyRate() {
а CurrencyRateFetcher это не класс-планировщик?
в задании написано, что в нём делать:
"В payment_service создать бин CurrencyRateFetcher, который содержит один единственный метод. Этот метод должен запускаться каждый день по cron-выражению, которое хранится в application.yaml.
"
Или ты имеешь ввиду что на всё приложение один класс-планировщик и он запускает все методы, которые запускаются по расписанию?
Тогда зачем класс CurrencyRateFetcher?

2024-10-05 08:45 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +                .uri(uriBuilder -> uriBuilder
поправил

2024-10-05 08:47 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        String baseCurrency = currencyRateCache.getBaseCurrency();
Чтобы можно было посмотреть в кэше, какая там базовая валюта лежит.
Или ты к тому, что String baseCurrency нужно не из кэша брать, а из другого места и потом в кэш помещать?

2024-10-05 08:47 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String baseCurrency;
Чтобы можно было посмотреть в кэше, какая там базовая валюта лежит

2024-10-05 08:48 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
ну да, согласен, не туда подумал

2024-10-05 08:50 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            String message = "An empty list of the exchange rate was received from the exchange rate service.Currency exchange rate update failed";
поправил

2024-10-05 08:51 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +            throw new NullPointerException(message);
поправил

2024-10-05 08:57 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String date;
Если дата не сегодняшняя, то повод бить тревогу, по какой-то причине не выполнилось обновление кэша  - например внешний сервис поломался, или думаешь исключений.
if (rateDto == null) {
            String message = "An empty response was received from the exchange rate service.Currency exchange rate update failed";
            throw new RuntimeException(message);
        }

        if (rateDto.rates() == null) {
            String message = "The list of exchange rates was not received from the currency exchange service.Failed to update the currency exchange rate";
            throw new RuntimeException(message);
        }
Достаточно будет?
Как на практике происходит мониторинг работы?
Например как тут - внешний сервис перестал работать, мы не получаем от него данные, а для нас это критично, потому что это влияет на получение денег компанией.Нам нужно как-то срочно узнать об этом и починить, чтобы не прерывать денежный поток.
Делается анализ логов на конкретные исключения с сообщениями и если они есть в логе, то высылается уведомление на почту или как-то по-другому?

2024-10-05 09:03 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +    public CurrencyRateDto checkHealth() {
проверяет отработал ли метод обновления кэша и есть ли какие-либо данные об валютах

2024-10-05 09:04 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        currencyRateCache.setDate(rateDto.date());
написал выше

2024-10-05 09:11 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public Map<Currency, Double> checkHealth() {
поправил

2024-10-05 09:12 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
я целиком поле currencyRate перезаписываю при обновлении курса валют, если ConcurrentHashMap перезаписывать оно не будет работать как ReadWriteLock

2024-10-05 10:42 UTC, KarabbasBarabas commented on src/main/resources/application.yaml
> +  access_key: 2013557734a6dbc4c96e59020af22c48
Не против, но через файл я сделал, чтобы  потренироваться

2024-10-05 10:49 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    @Scheduled(fixedDelayString = "${currency-rate-fetcher.fixedDelay}")
поправил

2024-10-05 16:28 UTC, mysosnovskaya requested changes

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public void updateActualCurrencyRate() {
CurrencyRateFetcher этот как раз класс-планировщик. Но у тебя в него ещё ответственность контроллера залезла (эндпоинт), поэтому это было неверно. 
Классы-планировщики разные на разные действия) Вот сейчас у тебя всё ок. Только аннотация RestController осталась над этим классом, надо удалить)

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/client/CurrencyClient.java
> +public class CurrencyClient {
Красота 👍

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
Так, а что может сломаться? Приведи пример. Возьмем три потока, два читают из ConcurrentHashMap, третий его перезаписывает. В какой момент и кто из них получит что-то ошибочное, что нас не устроит?

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyService.java
> +        String baseCurrency = currencyRateCache.getBaseCurrency();
В идеале кэш ничего не должен знать о какой-то логике. Он просто хранит те данные, которые ему поручили хранить. 
Но как минимум - да, нужно брать не из кэша и в кэш помешать. Как максимум - я бы сделала кэш таким: `Map<Currency, Map<Currency, Double>>`, где первая Currency - это базовая валюта. Но это задел на будущее (который может не оправдаться), поэтому так делать необязательно.

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private String date;
Да, через уведомления на почту/в телеграмм/в другой мессенджер. Нам нужно узнать о том, что что-то не обновилось, сразу, как это случилось, а не тогда, когда кто-то начал пользоваться кэшем. И эта ошибка точно не должна показываться пользователям, они не виноваты =) Тут можно дальше рассуждать, насколько критично, если какое непродолжительное время пользователи будут пользоваться старыми данными, и если критично, то что делать. Но это с аналитиком. Думаю, для этой задачи это уже перебор) Поэтому я бы об этом здесь не думала. 
Дату давай оставим, раз уже сделал. Это в любом случае идея в правильную сторону и это действительно нужно мониторить. Просто в рамках этой задачи такого не предполагалось =)

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateController.java
> +        return service.checkHealth();
По логике он должен проверять, являются ли данными актуальными, т.е. дата в кэше - сегодняшняя или нет. А возвращать полностью все курсы валют - это уже перебор. А кстати, сейчас подумала, что лучше было бы не дату в кэш добавить, а дату последнего обновления вместе со временем.

2024-10-05 16:28 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +  cron: 0 1 0 * * * # раз в сутки в 00:01
А если сервис запустился в 00:05, то ему целый день стоять без данных?) Или я чего-то не увидела?)

2024-10-05 19:04 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
Перезапись является атомарной?(запутался немного)
Если нет, то поток, который будет читать может получить null и не пройдёт конвертация валют и платёж

2024-10-05 19:07 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +    public void updateActualCurrencyRate() {
поправлено решение задачи

2024-10-05 19:13 UTC, KarabbasBarabas commented on src/main/resources/application.yaml
> +  cron: 0 1 0 * * * # раз в сутки в 00:01
PostConstruct висит на методе контроллера

2024-10-06 18:43 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateController.java
> +        return service.checkHealth();
поправил

2024-10-06 23:16 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
Да, перезапись атомарная

2024-10-06 23:19 UTC, mysosnovskaya requested changes
Поправляй два последних коммента и разрешай конфликты и будем мержить)

2024-10-06 23:19 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +@Controller
Зачем это здесь? Это не нужно, класс не является контроллером

2024-10-06 23:19 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/currency/CurrencyRateCache.java
> +    private Map<Currency, Double> currencyRate = new HashMap<>();
Да, перезапись атомарная

2024-10-07 21:13 UTC, KarabbasBarabas commented on src/main/java/faang/school/paymentservice/controller/CurrencyRateFetcher.java
> +@Controller
поправил

2024-10-08 19:05 UTC, mysosnovskaya approved these changes

2024-10-08 19:05 UTC, merged