Feature bjs2 27268
CorporationX/payment_service pull request #69
Opened 2024-10-05 05:27 UTC by mktlamer

2024-10-05 07:45 UTC, Rashit86 commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @PostConstruct
А это точно корректно использовать Scheduled вместе с PostConstruct? Логически это странно, потому что postConstruct это метод, который вызывается только один раз. Т.е он вызывается в той последовательности действий, которые выполняет спринг при создании бина. А аннотация scheduled говорит что этот метод должен вызывать с определенной периодичностью, что нелогично. Может в CurrencyFetcher просто сделать отдельный  метод @Scheduled(cron = "${cron.currency-rate-fetcher}")
    public void fetchCurrencyRates() {
        currencyService.currencyRateFetcher();
    }
А в том случае если тебе надо, чтобы данные подтянулись сразу при старте приложения, оставить в том же виде postConstruct, но убрать над ним Scheduled. А если не надо сразу подтягивать, то вообще убрать postConstruct

2024-10-05 08:05 UTC, Rashit86 commented on src/main/java/faang/school/paymentservice/client/ExchangeRates.java
> +                .onErrorReturn(new ExchangeRatesDto());
логичней вернуть Mono.empty()

2024-10-05 08:08 UTC, mktlamer commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @PostConstruct
Не знаю на сколько корретно, но это работает. Логика такая. При старте мы не знаем redis пустой или там что то есть, поэтому запускаем метод через Postconstruct , чтобы на всякий случай подтянуть свежие данные. А затем работает Scheduled, который делает тоже самое, но с заданным периодом

2024-10-07 16:18 UTC, mikhailov26 requested changes
Переделать по моему сообщению в дискорде, и постараться найти другое решение вместо @postconstruct, действительно напоминает изобретение велосипеда)

2024-10-10 18:26 UTC, mikhailov26 approved these changes

2024-10-10 18:26 UTC, merged