task: Обменный курс | feature-BJS2-26139
CorporationX/payment_service pull request #73
Opened 2024-10-08 15:18 UTC by Varrankin

2024-10-08 19:40 UTC, Silencemess1ah reviewed
*LGTM*

2024-10-08 19:40 UTC, Silencemess1ah commented on src/main/resources/application.yaml
> +    fetch-cron: "0 0 0 * * *"
Да что ж вы себя не бережете! Одна пароли оставляет от гугловского сервиса, второй ключами бросается
https://github.com/user-attachments/assets/c7e86797-ca0b-4716-8dfa-d74645f708cf

2024-10-08 21:43 UTC, mysosnovskaya requested changes

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +    private final WebClient webClient;
Лучше выделить отдельный класс-клиент с одним методом fetchRates, иначе тебе будет сложно тестировать этот класс)

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +        fetchRatesFromApi().subscribe(currencyRates::putAll);
С subscribe хорошо 👍

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +                        .queryParam("base", "USD")
Все эти валюты лучше брать из конфига

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    fetch-cron: "0 0 0 * * *"
Это не страшно, это пусть будет) Иначе никто кроме Димы не сможет запустить этот сервис)) Нам такое тоже не надо

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @Retryable(retryFor = {ConnectException.class}, backoff = @Backoff(delay = 1000, multiplier = 1))
А ConnectException разве может возникнуть? Если ты имел в виду, что это webclient вернет, то у тебя там doOnError висит, где просто логгирование, в этом случае точно может быть ConnectException?

2024-10-08 21:43 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +                .map(ApiResponse::getRates);
Тут точно null не будет (имею в виду getRates вернет null)?

2024-10-09 09:14 UTC, Varrankin commented on src/main/resources/application.yaml
> +    fetch-cron: "0 0 0 * * *"
а где по правильному хранить ключи и пароли?

2024-10-09 09:22 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @Retryable(retryFor = {ConnectException.class}, backoff = @Backoff(delay = 1000, multiplier = 1))
как я понял данная ошибка вылетит на этапе .retrieve(), т.е не дойдет до doOnError. Я долго размышлял как правильно сделать, сначала хотел исключить ошибки которые при которых не надо дергать апи повторно например HttpStatusCodeException но таких ошибок оказалось очень много, потом решил все ошибки закинуть при которых надо повторно метод запустить, 

нашел вот такие:

1. TimeoutException: В случае, если запрос занимает больше времени, чем предусмотрено временным ограничением, при попытке подключения или ожидания ответа.

2. ConnectException: Возникает, когда невозможно установить соединение с сервером. Это может быть связано с сетевыми проблемами или недоступностью сервера.

3. UnknownHostException: Когда доменное имя не может быть разрешено в IP-адрес, обычно из-за проблем с DNS или неверного имени хоста.

4. SSLException: Ошибки, связанные с SSL/TLS-соединением, например, когда сертификат сервера не может быть проверен.

5. IOException: Общие ошибки ввода/вывода, которые могут происходить в процессе сетевого взаимодействия.

6. HttpStatusCodeException: Когда сервер возвращает статус HTTP, который не 2xx, и этот статус не обрабатывается явным образом в коде.

подумал что из них только при 2-ой ошибке имеет смысл запускать повторно

2024-10-09 09:31 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +    private final WebClient webClient;
ты имеешь в виду вынести метод fetchRatesFromApi и class ApiResponse в отдельный класс и тогда при тестировании нам можно будет замокать бин нового класса а не дублировать все из теста fetchRatesFromApi ? или я что то не правильно понял, в чем конкретно сложность с тестированием будет ?

2024-10-09 11:18 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +                .map(ApiResponse::getRates);
не должен, если ответ нам придет мы .bodyToMono(ApiResponse.class) и тогда он не может быть 0, ну в теории если нам не придет валюты тогда да, но так не должно быть, я на всякий проверку написал, если это лишнее удалю

2024-10-09 21:14 UTC, mysosnovskaya requested changes

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +    private final WebClient webClient;
Да, так. Когда будешь тестировать CurrencyService, то ты сможешь сделать мок только для WebClient, а так как у тебя потом у WebClient много методов вызываются по цепочке, то это всё будет очень сложно задать в тесте. Ну и в целом принято классы-клиенты выделять отдельно, не смешивая ни с какой другой логикой

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/WebClientConfig.java
> +public class WebClientConfig {
Этот класс должен быть в пакете config, а не в service

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    fetch-cron: "0 0 0 * * *"
Используются разные защищенные хранилища, из которых подтягивается информация. Например, hashicorp vault

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @Retryable(retryFor = {ConnectException.class}, backoff = @Backoff(delay = 1000, multiplier = 1))
> как я понял данная ошибка вылетит на этапе .retrieve(), т.е не дойдет до doOnError

Дойдет, она там залоггируется, но дальше исключение всё равно пойдет. Метод всё равно его выкинет

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @Retryable(retryFor = {ConnectException.class}, backoff = @Backoff(delay = 1000, multiplier = 1))
> подумал что из них только при 2-ой ошибке имеет смысл запускать повторно

По первой тоже нужно. Мало ли, со второго раза получится подключиться и получить ответ

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +                .onErrorResume(error -> {
Сейчас у тебя onErrorResume перехватит исключение, повторно его залоггирует (после doOnError) и создаст ApiResponse. Таким образом, исключение не будет проброшено дальше и  Retryable не отработает. А надо бы)

2024-10-09 21:14 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/CurrencyRateFetcher.java
> +    @Retryable(retryFor = {ConnectException.class}, backoff = @Backoff(delay = 1000, multiplier = 1))
Я очень рада видеть такой ответственный подход к работе, впечатляет! Ты молодец 👍

2024-10-11 14:14 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/service/CurrencyService.java
> +                .onErrorResume(error -> {
согласен)

2024-10-11 19:24 UTC, mysosnovskaya requested changes
Давай ещё над неймингом и расположением классов поработаем и смержим)

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/FetcherRatesFromApi.java
> +public class FetcherRatesFromApi {
CurrencyRatesClient (такие классы стандартно называют клиентами, поэтом так будет лучше)

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/FetcherRatesFromApi.java
> +    public Mono<Map<String, Double>> fetchRatesFromApi() {
Просто fetchRates - неважно откуда)

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/FetcherRatesFromApi.java
> +package faang.school.paymentservice.service.exchangerate;
Классы-клиенты находятся в отдельном пакетике client, т.е. у тебя это будет faang.school.paymentservice.client

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/ApiResponse.java
> +package faang.school.paymentservice.service.exchangerate;
А это dto класс. Его можно в пакет с остальными dto положить

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/CurrencyRateFetcher.java
> +public class CurrencyRateFetcher {
Так тоже ок, но можно в названии подчеркнуть, что это планировщик. FetchCurrenctRateScheduler

2024-10-11 19:24 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/service/exchangerate/CurrencyRateFetcher.java
> +        currencyService.updateCurrencyRates();
Добавить бы логов)

2024-10-14 13:45 UTC, Varrankin commented
привет) все поправил. Я так понимаю осталось тесты написать?  Или тут лучше дождаться когда интеграционные тесты пройдем? просто ты написала: "Давай ещё над неймингом и расположением классов поработаем и смержим)"

2024-10-14 20:36 UTC, mysosnovskaya commented
Здесь можно без тестов, т.к. юнит тестами особо нечего тестировать, логики никакой. Интеграционные подошли бы, но давай их оставим на другой раз)

2024-10-14 20:36 UTC, mysosnovskaya approved these changes

2024-10-14 20:36 UTC, merged