BJS2-40421 Оплата через DMS - 2
CorporationX/payment_service pull request #89
Opened 2024-10-26 21:42 UTC by ilu23ilu23

Клиент инициирует платеж, отправляет запрос ко мне в пэймент, я валидирую, проверяю идемпотентность, присваиваю статус Пендинг, сохраняю операцию, далее по аннотации дергается аспект, который отправляет в аккаунт сервис через редис дто с данными и типом операции - Авторизейшн, далее у этих операций есть время, когда они должны быть автоматически клирингованы, если до этого времени клиент отменит операцию своим запросом, то происходит апдейт операции на статус Канцелед и снова дергается аспект через аннотацию и отправляется инфа о том, что запрос отменен и тип операции Канцелятион, если же клиент подтвердил операцию в ручном режиме или вышло время для автоматического подтверждения, то снова происходит апдейт данных, присваивается статус Конфирмед, дергается аспект, отправляется в редис инфа с типом операции Клиринг, и если же в процессе клиринга произошла какая-то ошибка, то сущность снова апдейтится со статусом Фэйлед, дергается аспект и уже отправляются данные с типом операции Эррор.

2024-10-27 08:29 UTC, sultan-inked commented on src/main/java/faang/school/paymentservice/validator/PendingOperationValidator.java
> +        }
Разве не проще аннотации на дто повесить? Возможно чего то не понял

2024-10-27 08:29 UTC, sultan-inked commented on src/main/java/faang/school/paymentservice/repository/PendingOperationRepository.java
> +    Optional<PendingOperation> findByIdempotencyKey(String idempotencyKey);
Методы возможно все таки стоит разделять строчками, сложно читать

2024-10-27 08:29 UTC, sultan-inked commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        Optional<PendingOperation> existingOperation = pendingOperationRepository.findByIdempotencyKey(operation.getIdempotencyKey());
Длинная строчка

2024-10-27 08:29 UTC, sultan-inked commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +    public void confirmOperation(UUID operationId, boolean isManual) {
Я бы сделал два метода, имхо

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplatewithJackson")
redisTemplateWithJackson
глаз резануло)

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/controller/PendingOperationController.java
> +    final PendingOperationMapper pendingOperationMapper;
private забыл видимо

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/controller/PendingOperationController.java
> +        return ResponseEntity.ok().build();
для пустого ответа лучше использовать 204 статус. 
ResponseEntity.ok() вернёт 200
@ResponseStatus(HttpStatus.NO_CONTENT)

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/exception/OperationNotFoundException.java
> +    public OperationNotFoundException(String message) {
message можно константой сделать, чтобы в конструкторе каждый раз не писать

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/mapper/PendingOperationMapper.java
> +
лишняя строка

2024-10-27 14:37 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/repository/PendingOperationRepository.java
> +    Optional<PendingOperation> findByIdempotencyKey(String idempotencyKey);
++

2024-10-27 14:37 UTC, cemeh666 commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +);
Оооочень большой отступ

2024-10-27 14:37 UTC, cemeh666 commented on src/main/resources/readmeKafka.md
> +Всё, контейнеры запущены, можно пулить ветку и тестить.
у кафки есть какой веб интерефейс, чтобы смотреть, что в ней?
если есть укажи как в него зайти и куда смотреть

2024-10-28 14:05 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +    public void confirmOperation(UUID operationId, boolean isManual) {
Можно, но лучше чтобы тут логика была, так понятнее

2024-10-28 14:06 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplatewithJackson")
А как по другому?)

2024-10-28 14:10 UTC, cemeh666 commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplatewithJackson")
у тебя **redisTemplatewithJackson**
а я прошу так **redisTemplateWithJackson** сделать

2024-10-28 14:14 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplatewithJackson")
А, понял, не заметил

2024-10-28 14:18 UTC, ilu23ilu23 commented on src/main/resources/readmeKafka.md
> +Всё, контейнеры запущены, можно пулить ветку и тестить.
Каф дроп для этого как раз, зайти по текущим настройкам на localhost:9101 в браузере

2024-10-30 16:52 UTC, 20cognosce requested changes

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/config/KafkaConfig.java
> +@Profile("kafka")
Что значит этот профиль? Ты в пропертях конфигурацию просто прописал, какой профиль

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/application.yaml
> +  kafka:
? 
И как другие будут запускать сервис без кафки

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    active: redis
Куда ты спрятал...

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    active: redis
kafka - это не профиль
redis - это не профиль

это конфигурации

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    bootstrap-servers: host.docker.internal:9092
Через докер всё равно делал

2024-10-30 16:52 UTC, 20cognosce commented on src/test/java/faang/school/paymentservice/service/OperationMessageServiceTest.java
> +class OperationMessageServiceTest {
Интеграционные тесты почему не завезли?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/config/KafkaConfig.java
> +@Profile("kafka")
@ConfigurationProperties
@ConditionalOnProperty(kafka/redis)

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/config/KafkaConfig.java
> +        return new KafkaTemplate<>(producerFactory());
Зачем ты второй инстанс создаешь, у тебя уже есть бин

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/config/KafkaConfig.java
> +    }
?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplateWithJackson")
Может дополнить уже имеющийся RedisTemplate? А не второй бин создавать ради сериализатора

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/publisher/kafka/KafkaEventPublisher.java
> +    }
Ты таблицы в базе данных тоже через джава код создаешь?
PostgresTable.createNewColumn

Можно разделить настройку кафки (не через приложение, а либо руками, либо отдельными скриптами) и подключение к ней, это не правильно

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE INDEX index_pending_operation_status_clear_scheduled_at ON pending_operation (status, clear_scheduled_at);
На что ты индексы создал...
На статус и на дату? Зачем?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE TABLE pending_operation (
Почему таблица называется pending_iperation, pending - это и есть статус?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +    updated_at timestamptz DEFAULT current_timestamp
Форматирование столбцов

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/validator/PendingOperationValidator.java
> +        }
Ты не можешь это делать, нет, ты за это не отвечаешь

Султан рисовал архитектуру задачи, что сейчас фактически реализовано соответствует?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/mapper/PendingOperationMapper.java
> +    @Mapping(target = "id", expression = "java(java.util.UUID.randomUUID())")
Ты не можешь так генерировать айдишник, это должен делать JPA

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        pendingOperationValidator.validateIdempotencyKey(operation.getIdempotencyKey());
Где он задается? С фронта приходит?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        log.info("Operation initiated with ID: {}", operation.getId());
Баланс ты не валидируешь, удалить
account_service сам решает, достаточен баланс или нет, ты только запрашиваешь

save метод сам генерирует id, и возвращает сущность, с сохранённым в базе id

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        pendingOperationRepository.save(operation);
Есть только операция.
PENDING
CANCELLED
CLEARED
Это всё её статусы

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/aop/aspects/PendingOperationMessageAspect.java
> +        log.info("Publishing message with operation ID: {} and operation type: {}", operationId, operationType);
Какой это ужас...
Один раз плохому научил и теперь везде у нас аспекты будут

Отправка события в account_service - **неотъемлемая** часть метода твоего сервиса, не нужны тут аспекты, удали всё это

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/OperationMessageService.java
> +    @Autowired
Зачем ты тут написал autowired, он ничего не делает

Конструктор через ломбок можешь сгенерировать

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/OperationMessageService.java
> +                .orElseThrow(() -> new RuntimeException("Operation not found with ID: " + operationId));
А можно не id, а сразу сущность
Из метода сервиса сразу вызывай после сохранения в БД через saveAndFlush

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/OperationMessageService.java
> +                .orElseThrow(() -> new RuntimeException("Operation not found with ID: " + operationId));
Можешь асинхронно вызывать, @Async хорошо ложится на этот метод

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/repository/PendingOperationRepository.java
> +    Optional<PendingOperation> findByIdAndStatus(UUID id, OperationStatus status);
Не понимаю, чем поиск по id будет отличаться от поиска по id и статусу

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        operation.setUpdatedAt(LocalDateTime.now());
Можно аннотациями апдейтить таймстемпы

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +                pendingOperationValidator.validateAutomaticConfirmation(operation);
Так
Я не понял

С каких пор мы инициализируем клиринг без какого либо ответа от аккаунт_сервиса? Тебе аккаунт_сервис должен ответить, ЧТО ЗАРЕЗЕРВИРОВАЛ СУММУ НА ЭТАПЕ АВТОРИЗАЦИИ И ГОТОВ К СПИСАНИЮ

Создаем - списываем - создаем - списываем, никого не спрашиваем, как красиво...

Вы с Султаном прорабатывали архитектуру?

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/controller/PendingOperationController.java
> +    public ResponseEntity<UUID> initiateOperation(@RequestBody PendingOperationDto operationDto) {
Объясни как ты реализовал идемпотентность

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/validator/PendingOperationValidator.java
> +        }
Что это, господа, что это за дизайн...

2024-10-30 16:52 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/validator/PendingOperationValidator.java
> +        }
Это вообще не проверка, это шляпа, с балансом там может быть что угодно, ты тут никакие блокировки не предпринимаешь и знать не можешь об актуальном состоянии баланса.

10 юзеров запросили с одного баланса по тысяче рублей, уже ими покупки оплатили, уже сами себе клиринг подтвердили. И потом по редису до аккаунт_сервиса доходит 10 платежей, а денег зарезервировал он только для одного, остальные 9 ушли в ошибку, а нам тут пофиг ваще

2024-10-31 08:04 UTC, ilu23ilu23 commented on src/main/resources/application.yaml
> +    bootstrap-servers: host.docker.internal:9092
Я локально у себя его поднял, в инфру не лазил, у других сломаться ничего не должно

2024-10-31 08:05 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/config/KafkaConfig.java
> +    }
Это общий метод для создания топиков, чтобы его реализация была уже непосредственно в паблишере, вдруг еще какой паблишер сделать нужно будет

2024-10-31 08:08 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/config/RedisConfig.java
> +    @Bean("redisTemplateWithJackson")
template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
С дженериком у Султана не работает, но его использует Евгений в своем коде, поэтому чтобы не ломать код, и чтобы работало у Султана, пришлось так сделать

2024-10-31 08:29 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE INDEX index_pending_operation_status_clear_scheduled_at ON pending_operation (status, clear_scheduled_at);
У меня есть джоба, которая периодически проверяет в бд по этим полям операции, и когда время подошло, меняет их статус, поэтому я тут решил, что если это частый запрос, то лучше сделать составной индекс по этим двум полям.

2024-10-31 08:29 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE INDEX index_pending_operation_status_clear_scheduled_at ON pending_operation (status, clear_scheduled_at);
В задании сказано - подумайте куда лучше создать индексы

2024-10-31 08:31 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE TABLE pending_operation (
Переводится как "ожидающая выполнения операция"

2024-10-31 08:33 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        pendingOperationValidator.validateIdempotencyKey(operation.getIdempotencyKey());
Да, с фронта приходит, если я буду создавать, то идемпотентность не соблюсти

2024-11-05 20:55 UTC, 20cognosce requested changes
А где прослушивание сообщений от Султана об успешном клиринге? Не увидел, должно быть, потому что и на этапе клиринга может оказаться ошибка на стороне account_service, которая заставит всю транзакцию откатить, а ты уже всё применил у себя

В целом супер гуд, машина 💪

Нюансы доделать

2024-11-05 20:55 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +CREATE INDEX index_pending_operation_status_clear_scheduled_at ON pending_operation (status, clear_scheduled_at);
Там также написано "если они необходимы"
Конкретно эти два индекса бесполезны или даже вредны, потому что поля по которым они создаются обладают слабой уникальностью

Такими индексами **условно** ты создал хэшмапу в которой два ключа, и каждому ключу соответствует значение из списка, в котором тысяча элементов

2024-11-05 20:55 UTC, 20cognosce commented on src/main/resources/application.yaml
> +          format_sql: true
Вырубайте sql логи, они для дебага

2024-11-05 20:55 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/ClearingJob.java
> +    @Scheduled(fixedDelayString = "${app.clearing.job.interval}")
Scheduled итак в отдельном потоке стартует

2024-11-05 20:55 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/ClearingJob.java
> +        operationsForClearing.forEach(operation -> {
Лучше тут не цикл, а асинхронные таски через экзекьютор сервис запускай

2024-11-05 20:55 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/PendingOperationService.java
> +        pendingOperationValidator.validateIdempotencyKey(operation.getIdempotencyKey());
Может все-таки соблюсти, если ключ идемпотентности генерировать по атрибутам?
От кого, кому, тип операции, сумма
Они ведь статичны

И условно за последнюю минуту генерировать по всем этим полям хэш-код, который будет и ключом идемпотентности

Если отправлять сколько угодно запросов с такими же параметрами в течение минуты, то вторая операция не пройдет

Подумай над такой фичей

2024-11-05 20:55 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/dto/OperationMessage.java
> +public class OperationMessage {
Один топик всё-таки у вас и одно сообщение и на авторизацию и на клиринг
Ну окей, пойдет, но лучше разделить в реальных условиях, чтобы не путаться и не сортировать каждое сообщение по статусу в if else

2024-11-05 20:59 UTC, 20cognosce commented
Помимо этого, ребята, ждут от вас двоих ДЕМО к четвергу или воскресенью по этой задаче, она мощная и интересная, нужно показать вашу работу и функционал

2024-11-07 06:28 UTC, ilu23ilu23 commented on src/main/java/faang/school/paymentservice/service/ClearingJob.java
> +    @Scheduled(fixedDelayString = "${app.clearing.job.interval}")
Выше ты мне сказал, что сюда отлично подойдет аннотация Асинк)

2024-11-10 13:36 UTC, 20cognosce approved these changes

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/listener/kafka/AuthPaymentKafkaListener.java
> +    }
Нельзя было всех объявить в одном классе?

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/listener/redis/CancelPaymentResponseListener.java
> +    }
Аналогично, дублирование кода

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/publisher/kafka/KafkaEventPublisher.java
> +        );
Ну не от статуса зависит топик, нет
От бизнес-процесса зависит топик

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/CheckPaymentStatusService.java
> +    }
А в чем разница?

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/CheckingBalanceService.java
> +public class CheckingBalanceService {
Нельзя ветвить логику приложения опираясь на статус операции, это неправильный подход
Статус переименовывается, и что дальше, в кучу методов лезть менять, и еще бы не перепутать 

Просто в зависимости от того, из какого топика приходит событие, нужно вызывать тот или иной код.
От топика, не от статуса.

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/service/ClearingJob.java
> +        List<CompletableFuture<Void>> futures = operationsForClearing.stream()
Зачем тебе CompletableFuture
Почему не простой экзекьютор

Какой ответ ты ожидаешь для коллбека? Никакой

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/util/IdempotencyKeyGenerator.java
> +                operation.getClearScheduledAt().toString()
До минут может делать truncate

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/util/IdempotencyKeyGenerator.java
> +            return Base64.getEncoder().encodeToString(hash);
Хорошо, только меня интересует длина такого хэша

2024-11-10 13:36 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +    idempotency_key        VARCHAR(255) NOT NULL UNIQUE,
255 символов ты ставишь, окей

2024-11-10 13:36 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/payment_V001__create_pending_operation.sql
> +    idempotency_key        VARCHAR(255) NOT NULL UNIQUE,
А не вылезем ли мы за лимит при генерации

2024-11-10 13:36 UTC, 20cognosce commented on src/main/java/faang/school/paymentservice/mapper/PendingOperationMapper.java
> +        return IdempotencyKeyGenerator.generateKey(dto);
Не одобряю делать это в маппере
Лучше в сервисе, получили сущность к сохранению и тогда гегеним ей хэш

2024-11-10 13:37 UTC, merged