feature-BJS2-26132: PaymentService. Конвертер валют
CorporationX/payment_service pull request #93
Opened 2024-11-01 13:54 UTC by StepnovaVarvara

2024-11-02 10:29 UTC, Varrankin reviewed
гуд) как всегда пишешь чисто. @mysosnovskaya Мы с Варей встречались, обсуждали мотивацию повторного запроса курса валют, потому что мы и так их уже тянем, как думаешь зачем заново обращаться? Мы с Варей пришли к умозаключению что запрос валют через шадулер мы используем одним образом например для показа курса на сайте, а заново при каждой операции обращаемся для того чтобы была максимальная точность курса на данный момент, наверно бизнесу это важно должно быть

2024-11-02 10:29 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
а не много ли логики в контроллере? может вынести надо это куда-то?

2024-11-02 10:29 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/validator/ExchangeRateValidator.java
> +    public void validationExchangeRateResponse(ExchangeRateResponseDto responseDto) {
responseDto.getRates() == null можно проверить аннотацией в DTO, а responseDto == null  возможно можно переписать getCurrentExchangeRates с помощью Optional, и сразу проверку на null в коде проходить, на счет validationExchangeRateAmount думаю тоже можно подумать как его оптимизировать, как итог  ты сможешь сократить код, убрав лишние проверки и сервис валидации, ну и тесты лишние писать не надо:)

2024-11-02 10:29 UTC, Varrankin commented on src/main/java/faang/school/paymentservice/validator/ExchangeRateValidator.java
> +    public void validationExchangeRateResponse(ExchangeRateResponseDto responseDto) {
и как понимаю в логах ошибок лучше стектрейс выводить

2024-11-02 10:29 UTC, Varrankin commented on src/test/java/faang/school/paymentservice/service/exchangerate/CurrencyServiceTest.java
> +    public void whenConvertCurrencyShouldSuccess() {
нужна проверка на правильность расчетов, что у тебя result = корректно рассчитанной в ручную сумме

2024-11-02 10:29 UTC, Varrankin commented on src/test/java/faang/school/paymentservice/service/exchangerate/CurrencyServiceTest.java
> +    @DisplayName("Успешная конвертация валюты")
ну и под конец, если прям душить то, мы договаривались все писать на английском, мы же тип разработчики европейского уровня, надо привыкать и у тебя нарушено принцип изолированности теста, так как ты на мокаешь валидатор, если он не сработает то у тебя тест вылетит с ошибкой, хотя должен пройти, т.е ты зависишь от валидатора в данном тесте а не должна

2024-11-03 04:48 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/controller/PaymentController.java
тоже бросилось в глаза, но я не стала его трогать, тк у меня по заданию написано "добавте в метод котролера ... ". И честно говоря, я щас спустя время на него опять посмотрела и пришла к выводу, что тут 4 строчки, которые просто сообщение формируют, ничего, относящегося к бизнес логике, они не делают - делать для этого отдельный класс, как-то такое себе

2024-11-03 05:09 UTC, StepnovaVarvara commented on src/test/java/faang/school/paymentservice/service/exchangerate/CurrencyServiceTest.java
> +    public void whenConvertCurrencyShouldSuccess() {
окей, добавлила

2024-11-03 05:19 UTC, StepnovaVarvara commented on src/test/java/faang/school/paymentservice/service/exchangerate/CurrencyServiceTest.java
> +    @DisplayName("Успешная конвертация валюты")
по инглишу - я видимо пропустила этот момент, и мне никто до этого замечаний не делал, а я пишу так с самого начала)) Как я поняла про тесты нам сказали - делайте как хотите, тк это тесты, но все остальное на инглише. Но я перепишу не проблема! По валидатору - у меня тесты на валидатор написаны в отдельном классе на все вариаты исхода событий. Я просто не пойму что ты хочешь, типо добавить donothing в первую часть теста?! - а зачем это делать?? У меня есть verify с проверкой, что валидатор отработал

2024-11-03 13:34 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/validator/ExchangeRateValidator.java
> +    public void validationExchangeRateResponse(ExchangeRateResponseDto responseDto) {
попробую с этим что-то сделать

2024-11-03 13:49 UTC, StepnovaVarvara commented
> гуд) как всегда пишешь чисто. @mysosnovskaya Мы с Варей встречались, обсуждали мотивацию повторного запроса курса валют, потому что мы и так их уже тянем, как думаешь зачем заново обращаться? Мы с Варей пришли к умозаключению что запрос валют через шадулер мы используем одним образом например для показа курса на сайте, а заново при каждой операции обращаемся для того чтобы была максимальная точность курса на данный момент, наверно бизнесу это важно должно быть

ну да, я тут два варианта вижу: либо как мы с Димой обсудили в части оплаты по текущему курсу, либо задачку сделали, чтобы всем хватило задач на эту тему)

2024-11-03 20:20 UTC, mysosnovskaya requested changes
Вот и научилась интеграции делать, круто!) Просто скажу, что feign client это не единственный способ обратиться к другому сервису. Есть ещё web client (тоже очень часто используется), можно ещё встретить rest template (устаревший вариант, но на многих проектах всё ещё используют его). И другие варианты тоже есть)

2024-11-03 20:20 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/client/ExchangeRatesClient.java
> +@FeignClient(name = "exchangeRatesClient", url = "openexchangerates.org/api")
url - в конфиг

2024-11-03 20:20 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/client/ExchangeRatesClient.java
> +                                                             @RequestParam("base") Currency baseCurrency,
Тут совсем чуть-чуть стиль поплыл (на один пробельчик)

2024-11-03 20:20 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/config/WebClientConfig.java
> +@Configuration
О, нашла ошибку, молодец!)

2024-11-03 20:20 UTC, mysosnovskaya commented on src/main/java/faang/school/paymentservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handlerEntityResponseDtoNotFoundException(ResponseDtoNotFoundException e) {
handlerResponseDtoNotFoundException

2024-11-04 04:43 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/client/ExchangeRatesClient.java
> +                                                             @RequestParam("base") Currency baseCurrency,
готово

2024-11-04 04:43 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/config/WebClientConfig.java
> +@Configuration
у меня без этой аннотации проект не запускался

2024-11-04 04:45 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handlerEntityResponseDtoNotFoundException(ResponseDtoNotFoundException e) {
поправила, спасибо!

2024-11-04 04:49 UTC, StepnovaVarvara commented on src/main/java/faang/school/paymentservice/client/ExchangeRatesClient.java
> +@FeignClient(name = "exchangeRatesClient", url = "openexchangerates.org/api")
окей

2024-11-04 18:28 UTC, mysosnovskaya approved these changes

2024-11-04 18:28 UTC, merged